### ISSUE TITLE
9Anime API Error

### ISSUE THREAD

**Issue by Jtgroos** [anime-dl/anime-downloader#33]
Anime downloader [32manime[0m: anime-downloader 3.0.0

just installed all the software needed and used to the following commands,

anime watch --new 
and added Phi-Brain ~ Puzzle of God: The Orpheus Order
anime watch --list
opened Phi-Brain ~ Puzzle of God: The Orpheus Order
used download to try and download it 

got the following error:

Traceback (most recent call last):
  File "c:\users\kaidako\appdata\local\programs\python\python37-32\lib\site-packages\anime_downloader\sites\nineanime.py", line 33, in _get_sources
    url = get_stream_url(self._base_url, params)
  File "c:\users\kaidako\appdata\local\programs\python\python37-32\lib\site-packages\anime_downloader\sites\nineanime.py", line 30, in get_stream_url
    return data['target']
KeyError: 'target'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\kaidako\appdata\local\programs\python\python37-32\lib\site-packages\anime_downloader\sites\nineanime.py", line 42, in _get_sources
    url = data['target']
KeyError: 'target'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\kaidako\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\kaidako\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Kaidako\AppData\Local\Programs\Python\Python37-32\Scripts\anime.exe\__main__.py", line 9, in <module>
  File "c:\users\kaidako\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\kaidako\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\kaidako\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\kaidako\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\kaidako\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\kaidako\appdata\local\programs\python\python37-32\lib\site-packages\anime_downloader\cli.py", line 212, in watch
    list_animes(watcher, quality, download_dir)
  File "c:\users\kaidako\appdata\local\programs\python\python37-32\lib\site-packages\anime_downloader\cli.py", line 285, in list_animes
    for episode in anime:
  File "c:\users\kaidako\appdata\local\programs\python\python37-32\lib\site-packages\anime_downloader\sites\anime.py", line 74, in __getitem__
    ep_no=ep_id[0])
  File "c:\users\kaidako\appdata\local\programs\python\python37-32\lib\site-packages\anime_downloader\sites\anime.py", line 118, in __init__
    self.get_data()
  File "c:\users\kaidako\appdata\local\programs\python\python37-32\lib\site-packages\anime_downloader\sites\anime.py", line 143, in get_data
    self._sources = self._get_sources()
  File "c:\users\kaidako\appdata\local\programs\python\python37-32\lib\site-packages\anime_downloader\sites\nineanime.py", line 48, in _get_sources
    ) from e
anime_downloader.sites.exceptions.AnimeDLError: 9anime probably changed their API again. Check the issueshere https://github.com/vn-ki/anime-downloader/issues. If it has not been reported yet, please open a new issue

**Comment by vn-ki** [comment]
The latest release is 3.1.1. Please update and try again.

**Comment by vn-ki** [comment]
@Jtgroos Yeah. 9anime sometimes update their site too often, to keep away scrapers like this tool. 

That won't stop us anyway. :wink:

**Comment by vn-ki** [comment]
@Jtgroos Yeah. 9anime sometimes update their site too often, to keep away scrapers like this tool. 

That won't stop us anyway. :wink:
