### ISSUE TITLE
Invalid URL 'https:abc': No host supplied 

### ISSUE THREAD

**Issue by dibashthapa** [anime-dl/anime-downloader#581]
**Describe the bug**

Tried to download black clover anime from 9anime and didn't work. 

```
anime: anime-downloader 5.0.4
anime: Extracting episode info from page
anime: Found anime: Black Clover (Dub)
anime: Downloading to /home/dibash/anime-downloader
anime: Downloading Black Clover (Dub)-1
anime: ./Black_Clover_Dub/Black_Clover_Dub_001.mp4
ERROR: Invalid URL 'https:abc': No host supplied

````
**To reproduce**

```
anime dl 'https://www.9anime.to/watch/black-clover-dub.2y44/ep-24'
```

<details>
<summary>LOG</summary>

```
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.util[37065] INFO anime-downloader 5.0.4
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.util[37065] DEBUG Platform: Linux-5.8.18-1-MANJARO-x86_64-with-glibc2.2.5
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.util[37065] DEBUG Python 3.8.6
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.anime[37065] INFO Extracting episode info from page
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.helpers.request[37065] DEBUG -----
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.helpers.request[37065] DEBUG GET https://www.9anime.to/watch/black-clover-dub.2y44/ep-24
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.helpers.request[37065] DEBUG {}
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.helpers.request[37065] DEBUG {'user-agent': 'Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US) AppleWebKit/532.0 (KHTML, like Gecko) Chrome/4.0.211.2 Safari/532.0'}
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.helpers.request[37065] DEBUG -----
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.session[37065] DEBUG cached request
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.helpers.request[37065] DEBUG https://www12.9anime.to/watch/black-clover-dub.2y44/ep-24
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.helpers.request[37065] DEBUG /tmp/animedlgecb3gqf/tmposxftfif
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.helpers.request[37065] DEBUG -----
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.helpers.request[37065] DEBUG GET https://www.9anime.to/watch/black-clover-dub.2y44/ep-24
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.helpers.request[37065] DEBUG {}
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.helpers.request[37065] DEBUG {'user-agent': 'Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US) AppleWebKit/532.0 (KHTML, like Gecko) Chrome/4.0.211.2 Safari/532.0'}
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.helpers.request[37065] DEBUG -----
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.session[37065] DEBUG cached request
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.helpers.request[37065] DEBUG https://www12.9anime.to/watch/black-clover-dub.2y44/ep-24
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.helpers.request[37065] DEBUG /tmp/animedlgecb3gqf/tmpj39zln44
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.helpers.request[37065] DEBUG -----
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.helpers.request[37065] DEBUG GET https://9anime.to/ajax/anime/servers?id=2y44
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.helpers.request[37065] DEBUG {}
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.helpers.request[37065] DEBUG {'user-agent': 'Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US) AppleWebKit/532.0 (KHTML, like Gecko) Chrome/4.0.211.2 Safari/532.0'}
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.helpers.request[37065] DEBUG -----
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.session[37065] DEBUG cached request
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.helpers.request[37065] DEBUG https://www12.9anime.to/ajax/anime/servers?id=2y44
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.helpers.request[37065] DEBUG /tmp/animedlgecb3gqf/tmponcozlkj
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.anime[37065] DEBUG EPISODE IDS: length: 140, ids: ['33370f73294be4f313d134902446fbb852c1a0de0226b6c484770165f2f5e9a7', '866369e704802a76144b3b3f4e86d6aa31fdf41385d5193b0aa9df8f1bc0abd4', '401d58adaf5bb91d1f6ede6b4c99b0f363f2c06c022763cde24ff2df97cfdffc', '36853edf16049566bd872c833ff7474bc3e73c711a8b76f1c884608a65b170f7', '231b16012e9554f438ca000422c163fddf01f4ea2ab4fad4296242b567981eb4', '777b164ba31e800a7375e4eede23d5bf964459cf33f8652c0296913ad6f9b4bd', '226300486a97bdc624fb5b68ddf1c68f151103e063e6a136ce47c07bd5f770bd', 'c03c98c20f2b5398a8b928536182f3870819feaccbe13924f7259e39e7c848a5', '633fd4554d45e821b7b86bb503c18e2bf3933f1b02f002fe2ef1046d0a272a46', 'bd52ef073f937dee1044859849e50b0d744d0db7d037cec27e8c87fb229404af', '47938c03117df1b2cd70918973f0d2b450afcf5d0c6e9fadf8e4c618f895883d', 'e1774d2546bc3fec28e91ebf9b6ed3bfb7704572eb635f92738202a4ddb49042', 'cf1468363ff18f13cc51057107e8583ae0de669722810d57d0392bb99b5eadfd', 'f52978c3758bfbdd8fa221effd7c5e26780263de263bea00429588177568b3ca', '1d8d4a70fb3eeec04d9204911f34542e5d0509b9439cbe45e19f9e09d1f4c9f6', '5c218df1e62e455ba4be1eb4b6cdfbf8227db88ce46de07c2467bde626f7212b', '9253d0f3b163fe48b397689d74a6c537a3295da4362162f3c4190f4482b6b194', '1b463ba3c3a1e344131b8b0d212defc98e927a8b9cd559cfd32a87b04c5ba744', '139ef74191b96b34a6ee8b7412d6ced6574540824ddfe3cf3dc841cfca8b44e9', 'c41a3eb219c2be008cf835c89460dd4c44d3bdbaf204396cf4e4e3c96faf998d', 'de2c2cbfae285d54e72fd1144aa7803cc740c82b55dad01215f33e9048e791b8', '325884aaea60330164927c169081eb1127946d8097a63909fc4dc25a86cf0460', '50675491aa716157f6639a7edf6b00b1eab0245a962af944e5db92cba6be91c1', 'ae7e7377d9be718e7ab474dea9b3763c08af4dd390189aa72bf6e6a3a0bae2c2', '631c136b9b8f2fe83da02a412eec4e650297bdc52b00a945f978527ac09708a3', '007b29c52873c3db69af27ef0717d487fe3fbd26a9c5a16404eb2a8206220ffb', 'd127ebfffde8a9c14f7b84974d1b1df12607cb91b7c8230a516548595d3bb047', '6737b155421e27a4d30cc94bbb9e26a221f6f48033d7d242b429e6a30801f309', 'decba2f183327cb7970f10578adbafc07dcfddd3d5b51a04f677adb26366cf10', '256448dc47af9c6e0d2b90e8972040e068a8be79cae39fbf566a2a7aef3e9063', 'd765ca774287154b7d0b77e5b6f13bc4f92a81aa7ab0fed8af7397c453e37676', 'a083317ae4b14f71cc10b7f3180031e01fad22003cde8a8494bd3338f8637c95', '1257c52b8d0b6e9282049a3783aa0c3bc7a71b446892998a6ca98f5e6938da29', 'fa978aad7273a9200bcc09781019c7e8d1fe6ea7a048a0e5a1195e2700a75693', 'e95253e3b36a613570da3fbfc8814193ced8bcaae532be72db8c5d72d9283f1e', 'aaa99a86a9ec8162e479ad66c6ccc97ef0853763b47e85d33cf844a9af438f32', 'a12d997a8f7031df05324606207da69fc3894f12b24a8d3bbc64bacd93f49555', '2622ce9d3e1620dd5b901a8c76aa0452c7f79d961dbb7354ce065f83cae6b7c7', '766ae75199ff52368a9d327035d8a0dacad72993b12d218e19fc9efaaf899a5b', '4c4132497888b2d4cbdcbec5ffbd08e722085f9bda861cd72874f3cd8d6420ed', '4821f37ae039dd992eea2738f9bd543344491c7cbb3f625034c763eb4088c5fd', '442b3b4b3b352ff3ab6169c6ea987855268e85e12ba8405411d12359be382c72', '3dcd55c209ba26fcc8af131f204f443ce57aac741b58be41739eee601cab6c92', '59ed66af0b31a9fdb25904f0aa7f08c9370fe31f098a4e841331a79872f1d880', '034e0da8fcad87bb8be992810f0f6bd5e949d5fe137700358022dce6fc0e76de', '4a4814426a35f64ef15e6f104425aeb6610405fdaa23bda3f2a2a9578c250060', 'fefdd4d54e5d9ec512c0ad62c5177d98d5c85516dfeb53ebbb50d84155a6c934', 'da54189f40461d88e11bf5daa0951a5dc7a2b2009f95cc7f03ab8ad784acbaf4', '45afb70c9aab34455718813ec00fa15c80e4ef3963e23bcbd711450a68ae605e', '08bc7853142830987b263f7dabb3554cb53280011d69e1b4f09450f0110e00da', '9a4d579be5b1352ef4c01cd1688f57b7f0929ba1887bd822adcbb6bf90ef2805', '8639f30ca0e28e493d359daaba90adc9a5a4c50f3b578f49484420f468c55e6e', 'c9aacde6ebeafd6d354ce0d2031d4177fccd9c8e1e92a4ba5aa9ff0861bef99f', 'f0e94b173071257143ff7dec9a3961a3bf291faab86deb91c2b7b3cba6f5e831', 'b57dbfa795dc1c3b53ff05fb70c328bbe1eae6e94eaf1b9c6a0aefc7a02a75c1', '88143e5c91e4620f621f1b2e178e4b5adc338b071d8f741a822ded93b37b57c6', 'e0a7a536d88f2033d0d3df016d3c098925b9e4cc11622b360b7d17edc9374cea', '618fce709ea219b285528cd5181dbed5e43122a84af80cedc22a9386fbce9323', '6af860176fd0c42eb12d49d7ee68003d1611573ff444afc606df464f7677dd78', '62105ad42419f82b9813071722fac1049d4e26e091eab84fa27024dffcdeb9af', '0cc72cdfd814ac4498ec17d49695b75c1a460018a685b645eb77cb569bfaee55', '9540e359078ad7b08df52dcf14eb3590a5f4b02d59f39498cfb3911ad04a9dea', '320d59e2a2f34534847ef8331e6c5562caf8f685e3132f9722a30bc894e8075a', 'dfbdd81ba44cbd6ca1e5b72456ee915c1a4d612a15f1a5146c96641950bf005f', 'b69023624a2409af2c9a3866f52fab6f25192f29e2114d073088f5d4bba1c1ee', 'c3bc9ae17d9f967ea08e422a8a6d9f512f8507170e270837c662df16ec8811a3', 'b14e9f11d866b8adf4687e893390562f83b9b4eb956758a49a467181870bfa8b', '04a882fe5ad9599356e5bae2a131d75f4379eafa0931c78306ca939d576692d1', '9126bed1a963da66d8a0ffe93b4209eae6c9f154733e1272e7d4bcb4fb0bfc3e', '6da36ba09374d1f769456f54b48ab1990ecc47786979fa30eda927da55157fa7', '3348758ff784548c4a3063c97b87e77de2148397eb0e1888b374c56079485be2', 'de339a73151849ebc5e2b27d7f4b400fc15fc23e976dbf898b2e9b4b4e401009', '89c81e405a4b26740a41e0e032050c4fa1e50544d32cbb39477b073eb3a1550c', '213fd1fcacb1b63b719f51d12075ec4ddee4c6c7e27224583aca61bb2c905c75', '24fd3ab44fd6dcd1c33a48b3715a33cac879cb43cfedcb46cb5bc1c3fb294ae2', '23c52b21eb958f908df0c51ac825080f3bfe7643d7448bbfc311b0bcb776a449', '305847c501368f49d0f2a67afe24ae758bc150427d1fd181fe6a190fa85c14ab', 'f18c2a91a3ae941e37163d93ee80d2a54b8f4a6b0488d5d7391c4bc0536275d3', '81de14dfb45af8b41e9bb0ba54b314eef84e0acde40e8750175b3e3bf32bebac', '40b797c886d27cc9c4c751574ae27280d1bc257fe8016f2884a9bc10da5760f7', '62eaa616fa8acd5e0146e1e011a6d2fc9334b98e062827c796c3f2c9b9fa6e09', 'aa9570e7023ddd3949226f9d79072666045908384b5f0e2a2d6dbcd4f104e7a6', 'e46d36753dc2d64074dca72034ef42c4589a1322a7599445926fed1644131d53', 'b8ca9883f7d1c1dd7f897fbecc5a650daca39bd342b8f09645012f338ced1b9b', 'a1abbad27a4ed9199f1eeddfee03961181668d5818094399e6724eac362b7530', '78343969fddc943a09a6d78e497117f061f94e053ee23fee42d324f2d3dc76e8', 'a407f6620f36c1b6d38a557282ab644c93748436896924b21bbcce4968a8b413', '227ad11116de6ca8b7ece3d6b8f64d3b1d01c9c860b764247daf709a2481ca54', '183bc3b746515b6a69948837b2960ec9f1f5e904a7223894d64c6630203e4a35', '110521be0eb068a2e1d7ed318230c1fcafcb30704b25cdb325d6d5534ef5972d', '846cdfc0f216ae632c22aace01f69e033dfc97b17b6551ac213978f3535c09cf', 'cb7067800a415b6ad0e69afee1a2de94f9ea199b743a69c5cddac5bab8d0864b', '2b4e80e9283f3afac693a23650c777bbe0318bd8d56d907d73056089f2cc7d04', '8b509d4ff1167a72f951d2ebd5edaa8e336e54213184f2f4d5b02f2859ffaa14', '2dfacef906ccf98a9bcbfef881cc546410516f69d51a6b6275030ebf10e75fc4', 'd7e05743741a068ae25e9a13bd184d387dcc0de08f513f5f672e78266406b297', '550d9d6a862e60623a3794bdf666e3d181add8a794cb0fd8711424babebbf65b', 'fdda4364f2709031e8355200aed2f6c9338f75ee0a1d18285c85fa394318d857', 'f2b7c4fe989ed3fd18394b23ac801ba62c110f73be74d76983beb2e8f81afe60', '424483ef5cb9734d546911ce309602a2470b57ed92f36bc36dc66ed0e137d583', '99801f882214f80e82eaadb8bd04f07182b1af6668d978d4843732359610a570', '932bac0c0c4170e95282769e566f2637f12ee1b2f93b72d7529031e5f2430d73', 'e016423c940701a15b509d8cb399e66d05237cf74ea9376472005527c95af80c', '1f1a4f2d44070a341d4749538b0bf97b9cfd8dd9c0d41a73c31b432b26a99e0a', '8c6a9ea5563d2fa5552ad6eefad1dcf5ad5b76a7bc290d9f0160c86a74cfdac4', 'e48bcda6a1c8bfef40eb79fd5a236194a7594f0954fdf562f6f42a364eab9ec0', '271b988519058a3e0eea9735e42963e769760011edb6a85b7bb511fcfcd07e52', 'ce49b87afca3963642f9608676f9db88c8a0dcd4adb90056de441b5cdda080d8', '1eb106f7e86f1e99cbca1acd8e74d37d6fc947ff601bf72a5cced9f9891de0c6', '740ffa4c67e8baa06a38a5ec4ba837f17d345a01ff7594948194bafbf0fa9eb4', '42660a4b1178289cbcb66f9e1f13d8fac37472a3bff4815ae76214224f35b195', '4d70ff93bc22fdb46a3a576c7bb7642feaf48bc27ee5d7187615a21fd024b090', '79786025ba7f5672cc03e8bf88543b550e9c9f61b21b390450f11917847c1e14', 'f61305237517e1332120def92e19ff0f705c2a135b4b851682196db807a0d3b1', '10b213863ef229831afef04c22ed130733736177c7b587fd4621ebf0b92509b2', '8a7694c1c60cf1a7f7c5fb0618535afa0065a8d5fb4d462cd62a3b01623199d6', 'c152459d17d018f34159a195687e7a06c0a9550530674f296c4b65d499aefa95', '4f071acbb733cd1e469488cc6977ee4a2ff08c9e7c2a78e16a188b309d788be4', '7ea31596525f26c65297441e7ce1531f672446a67e9d69e9e3e3c8962b37c0b0', '7c22e5a2e6b86883a6fb0555f7a57d9a6505fe0bfc994158dd31f8688ca34a2d', 'cabc40511722138d8978b0b032ccf9dd9580d4de169e599c36ba03c4298c5a6f', '8124d0baede9a836005a4dbc5d03c69e840c7d08ed4cbd07d8e355cafc3ec0eb', 'ad343c536251beae6bd448368cd7ed274663c01f0e259afcf2ee7156db451ed2', '0d90c51afc31fc7269fa37d064a58308cd22f54afbe91c9cec5ab5a0f2fc8962', '9b35fc53682f4ea738c87bc1a6d16c530c55538b70f0dbf941ff5bf517d1b0b8', '23e815bf1069f01bd3bf4a5fd4c2ea0d7aa419a60fd5305f4e8ea45721c98960', '450a315744ffd2d7f44acb0af557df1d6edcd338883f0fd9ed8f914b3a080634', 'a411073acdcfb059eaff4e2aaeb84ef1a1a6a907fc7002727bef4481545c35c6', 'b400c25ee786af6e5173839221d7ea23fdb9154e498c9b1b3d7701f862784232', 'aed604093e9ab9206bff4ace7af23b262ad040e4f5e384c9c923f31df45ccda1', '18854dc86b36515a2b55b101a43c904edac675c07df4a08028114c9e76401899', '9a30c69a5b2ec0466740700ae43b249d727d82a3fd239e2bd9ba8852ae826142', '5d306e7295a7c204b62a9c98894b25540dd4a61db1a8c28e688a6a369b4fcfc9', 'c68d00711144498d0f3a05b577a63426b88b044c70ff1b29b27dbc2e33d6a112', 'e81b3e85394c2144dde2bfe7d12bfb53a75f64a4cdc8b096ae64509246c1ad23', '7d24b847787f7a3b4630084f747c274051a19130b101ced9dcc4919599b6241d', 'e9ad7b0e2377678b5add2f135f4992666c70e6af358da7adbe396ca0e2c34cc6', '152e771a69c35ce9f9c0bd8e05f1f8e3222c65a99183a703c6a1572a06b24761', '6eb69309bdd11f1cbf133ec59b9c9a3e45216cbe765841b4e2ed62d04f5945e5', 'b5b7469f44684cf3ea283461ed31cbb4193ce3789f7eafd7e5aea919012de7ac']
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.commands.dl[37065] INFO Found anime: Black Clover (Dub)
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.commands.dl[37065] INFO Downloading to /home/dibash/anime-downloader
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.anime[37065] DEBUG Extracting stream info of id: 33370f73294be4f313d134902446fbb852c1a0de0226b6c484770165f2f5e9a7
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.helpers.request[37065] DEBUG -----
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.helpers.request[37065] DEBUG GET https://9anime.to/ajax/anime/episode?id=33370f73294be4f313d134902446fbb852c1a0de0226b6c484770165f2f5e9a7
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.helpers.request[37065] DEBUG {}
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.helpers.request[37065] DEBUG {'user-agent': 'Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US) AppleWebKit/532.0 (KHTML, like Gecko) Chrome/4.0.211.2 Safari/532.0'}
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.helpers.request[37065] DEBUG -----
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.session[37065] DEBUG cached request
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.helpers.request[37065] DEBUG https://www12.9anime.to/ajax/anime/episode?id=33370f73294be4f313d134902446fbb852c1a0de0226b6c484770165f2f5e9a7
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.helpers.request[37065] DEBUG /tmp/animedlgecb3gqf/tmp3zc0642n
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.nineanime[37065] DEBUG Videolink: https://streamtape.com/e/BajJDeG6p0IyAKj/?site=www12.9anime.to<
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.anime[37065] DEBUG Sources : [('streamtape', 'https://streamtape.com/e/BajJDeG6p0IyAKj/?site=www12.9anime.to<')]
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.helpers.request[37065] DEBUG -----
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.helpers.request[37065] DEBUG GET https://streamtape.com/e/BajJDeG6p0IyAKj/?site=www12.9anime.to<
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.helpers.request[37065] DEBUG {}
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.helpers.request[37065] DEBUG {'user-agent': 'Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US) AppleWebKit/532.0 (KHTML, like Gecko) Chrome/4.0.211.2 Safari/532.0'}
2020-11-27 20:26:03 dibash-vostro3590 anime_downloader.sites.helpers.request[37065] DEBUG -----
send: b'GET /e/BajJDeG6p0IyAKj/?site=www12.9anime.to%3C HTTP/1.1\r\nHost: streamtape.com\r\nuser-agent: Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US) AppleWebKit/532.0 (KHTML, like Gecko) Chrome/4.0.211.2 Safari/532.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Fri, 27 Nov 2020 14:41:04 GMT
header: Content-Type: text/html; charset=UTF-8
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Set-Cookie: __cfduid=d64457a0fb9b58da29068ea0f2d11e6d71606488064; expires=Sun, 27-Dec-20 14:41:04 GMT; path=/; domain=.streamtape.com; HttpOnly; SameSite=Lax; Secure
header: Cache-Control: private
header: Set-Cookie: _b=kube12; path=/
header: CF-Cache-Status: DYNAMIC
header: cf-request-id: 06abbf98560000cddf660b2000000001
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=sj2LXbxxbBKAhSUxbj5kXvvhheXaYiKfFOVm2Scg0ADv8f4M02MkUAy1LRMeeCwEbeotPlH1oev7rq7zPHrxxFVThH0IKsjB0Vea%2BnMhgA%3D%3D"}],"group":"cf-nel","max_age":604800}
header: NEL: {"report_to":"cf-nel","max_age":604800}
header: Server: cloudflare
header: CF-RAY: 5f8c9ba08b19cddf-CDG
header: Content-Encoding: gzip
2020-11-27 20:26:04 dibash-vostro3590 anime_downloader.session[37065] DEBUG uncached request
2020-11-27 20:26:04 dibash-vostro3590 anime_downloader.sites.helpers.request[37065] DEBUG https://streamtape.com/e/BajJDeG6p0IyAKj/?site=www12.9anime.to%3C
2020-11-27 20:26:04 dibash-vostro3590 anime_downloader.sites.helpers.request[37065] DEBUG /tmp/animedlgecb3gqf/tmp7d1j8keq
2020-11-27 20:26:04 dibash-vostro3590 anime_downloader.sites.anime[37065] INFO Downloading Black Clover (Dub)-1
2020-11-27 20:26:04 dibash-vostro3590 anime_downloader.downloader.base_downloader[37065] INFO ./Black_Clover_Dub/Black_Clover_Dub_001.mp4
Traceback (most recent call last):
  File "/home/dibash/.local/bin/anime", line 8, in <module>
    sys.exit(main())
  File "/home/dibash/.local/lib/python3.8/site-packages/anime_downloader/cli.py", line 53, in main
    cli()
  File "/home/dibash/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/dibash/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/dibash/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dibash/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dibash/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/dibash/.local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/dibash/.local/lib/python3.8/site-packages/anime_downloader/commands/dl.py", line 147, in command
    episode.download(force=force_download,
  File "/home/dibash/.local/lib/python3.8/site-packages/anime_downloader/sites/anime.py", line 427, in download
    downloader.download()
  File "/home/dibash/.local/lib/python3.8/site-packages/anime_downloader/downloader/base_downloader.py", line 68, in download
    if self.check_if_exists():
  File "/home/dibash/.local/lib/python3.8/site-packages/anime_downloader/downloader/base_downloader.py", line 40, in check_if_exists
    with requests.get(self.source.stream_url, headers=headers, stream=True, verify=False) as r:
  File "/home/dibash/.local/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/dibash/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/dibash/.local/lib/python3.8/site-packages/requests/sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "/home/dibash/.local/lib/python3.8/site-packages/requests/sessions.py", line 449, in prepare_request
    p.prepare(
  File "/home/dibash/.local/lib/python3.8/site-packages/requests/models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "/home/dibash/.local/lib/python3.8/site-packages/requests/models.py", line 391, in prepare_url
    raise InvalidURL("Invalid URL %r: No host supplied" % url)
requests.exceptions.InvalidURL: Invalid URL 'https:abc': No host supplied


```

**Comment by AbdullahM0hamed** [comment]
It would appear that the streamtape extractor is broken

**Comment by XanderThunder** [comment]
Is there another extractor which can be used? Like e.g. Vidstream

**Comment by AbdullahM0hamed** [comment]
Atm, 9anime only has streamtape

**Comment by XanderThunder** [comment]
Thank you for the quick fix. Appreciate all the work you guys are doing for us!!!

**Comment by dibashthapa** [comment]
@AbdullahM0hamed 
 ```
ERROR: Extra data: line 1 column 146 (char 145)
```
Now after reinstalling from github, i am getting this error with the same link I provided above

**Comment by AbdullahM0hamed** [comment]
Turns out that particular anime doesn't have streamtape, which seems to be the only server that is currently supported in nineanime.py. I'll look into adding support for other servers over the weekend
