### ISSUE TITLE
[BUG] Erai Raws: Episodes not being found

### ISSUE THREAD

**Issue by AbdullahM0hamed** [anime-dl/anime-downloader#645]
**Describe the bug**

No episodes found for anime such as `Jaku-Chara Tomozaki-kun`

**To reproduce**

```
anime dl -u tomozaki -p erai-raws  -c 1
```

<details>
<summary>LOG</summary>

```
2021-03-12 15:29:14 localhost anime_downloader.util[24830] INFO anime-downloader 5.0.7
2021-03-12 15:29:14 localhost anime_downloader.util[24830] DEBUG Platform: Linux-3.18.14-Quantum_Kernel-V1.0-J7velte-20180916-armv8l-with-libc
2021-03-12 15:29:14 localhost anime_downloader.util[24830] DEBUG Python 3.9.1
2021-03-12 15:29:14 localhost anime_downloader.sites.helpers.request[24830] DEBUG -----
2021-03-12 15:29:14 localhost anime_downloader.sites.helpers.request[24830] DEBUG GET https://check.ddos-guard.net/check.js
2021-03-12 15:29:14 localhost anime_downloader.sites.helpers.request[24830] DEBUG {}
2021-03-12 15:29:14 localhost anime_downloader.sites.helpers.request[24830] DEBUG {'user-agent': 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/532.0 (KHTML, like Gecko) Chrome/4.0.211.4 Safari/532.0'}
2021-03-12 15:29:14 localhost anime_downloader.sites.helpers.request[24830] DEBUG -----
2021-03-12 15:29:15 localhost anime_downloader.session[24830] DEBUG uncached request
2021-03-12 15:29:15 localhost anime_downloader.sites.helpers.request[24830] DEBUG https://check.ddos-guard.net/check.js
2021-03-12 15:29:15 localhost anime_downloader.sites.helpers.request[24830] DEBUG /data/data/com.termux/files/usr/tmp/animedl_w1kjv5x/tmps9nff7vv
2021-03-12 15:29:16 localhost anime_downloader.sites.helpers.request[24830] DEBUG -----
2021-03-12 15:29:16 localhost anime_downloader.sites.helpers.request[24830] DEBUG GET https://erai-raws.info/.well-known/ddos-guard/id/PY7XwCm25eC3I9VB
2021-03-12 15:29:16 localhost anime_downloader.sites.helpers.request[24830] DEBUG {}
2021-03-12 15:29:16 localhost anime_downloader.sites.helpers.request[24830] DEBUG {'user-agent': 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/532.0 (KHTML, like Gecko) Chrome/4.0.211.4 Safari/532.0'}
2021-03-12 15:29:16 localhost anime_downloader.sites.helpers.request[24830] DEBUG -----
2021-03-12 15:29:16 localhost anime_downloader.session[24830] DEBUG uncached request
2021-03-12 15:29:16 localhost anime_downloader.sites.helpers.request[24830] DEBUG https://erai-raws.info/.well-known/ddos-guard/id/PY7XwCm25eC3I9VB
2021-03-12 15:29:16 localhost anime_downloader.sites.helpers.request[24830] DEBUG /data/data/com.termux/files/usr/tmp/animedl_w1kjv5x/tmpy4fuloed
2021-03-12 15:29:16 localhost anime_downloader.sites.helpers.request[24830] DEBUG -----
2021-03-12 15:29:16 localhost anime_downloader.sites.helpers.request[24830] DEBUG GET https://erai-raws.info/anime-list/
2021-03-12 15:29:16 localhost anime_downloader.sites.helpers.request[24830] DEBUG {'cookies': <RequestsCookieJar[Cookie(version=0, name='__ddg2', value='PY7XwCm25eC3I9VB', port=None, port_specified=False, domain='.erai-raws.info', domain_specified=True, domain_initial_dot=False, path='/', path_specified=True, secure=False, expires=1647098963, discard=False, comment=None, comment_url=None, rest={'HttpOnly': None}, rfc2109=False)]>}
2021-03-12 15:29:16 localhost anime_downloader.sites.helpers.request[24830] DEBUG {'user-agent': 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/532.0 (KHTML, like Gecko) Chrome/4.0.211.4 Safari/532.0'}
2021-03-12 15:29:16 localhost anime_downloader.sites.helpers.request[24830] DEBUG -----
2021-03-12 15:29:16 localhost anime_downloader.session[24830] DEBUG cached request
2021-03-12 15:29:16 localhost anime_downloader.sites.helpers.request[24830] DEBUG https://www.erai-raws.info/anime-list/
2021-03-12 15:29:16 localhost anime_downloader.sites.helpers.request[24830] DEBUG /data/data/com.termux/files/usr/tmp/animedl_w1kjv5x/tmpy2mber2a
+--------+-------------------------+--------+
|      3 | Youjo Senki             |        |
|      2 | Tomie                   |        |
|      1 | Jaku-Chara Tomozaki-kun |        |
|--------+-------------------------+--------|
|   SlNo | Title                   | Meta   |
+--------+-------------------------+--------+
2021-03-12 15:29:19 localhost anime_downloader.util[24830] INFO Selected Jaku-Chara Tomozaki-kun
2021-03-12 15:29:19 localhost anime_downloader.sites.anime[24830] INFO Extracting episode info from page
2021-03-12 15:29:19 localhost anime_downloader.sites.helpers.request[24830] DEBUG -----
2021-03-12 15:29:19 localhost anime_downloader.sites.helpers.request[24830] DEBUG GET https://erai-raws.info/anime-list/jaku-chara-tomozaki-kun
2021-03-12 15:29:19 localhost anime_downloader.sites.helpers.request[24830] DEBUG {}
2021-03-12 15:29:19 localhost anime_downloader.sites.helpers.request[24830] DEBUG {'user-agent': 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/532.0 (KHTML, like Gecko) Chrome/4.0.211.4 Safari/532.0'}
2021-03-12 15:29:19 localhost anime_downloader.sites.helpers.request[24830] DEBUG -----
2021-03-12 15:29:19 localhost anime_downloader.session[24830] DEBUG cached request
2021-03-12 15:29:19 localhost anime_downloader.sites.helpers.request[24830] DEBUG https://www.erai-raws.info/anime-list/jaku-chara-tomozaki-kun/
2021-03-12 15:29:19 localhost anime_downloader.sites.helpers.request[24830] DEBUG /data/data/com.termux/files/usr/tmp/animedl_w1kjv5x/tmpn8u11m_6
2021-03-12 15:29:19 localhost anime_downloader.sites.helpers.request[24830] DEBUG -----
2021-03-12 15:29:19 localhost anime_downloader.sites.helpers.request[24830] DEBUG GET https://check.ddos-guard.net/check.js
2021-03-12 15:29:19 localhost anime_downloader.sites.helpers.request[24830] DEBUG {}
2021-03-12 15:29:19 localhost anime_downloader.sites.helpers.request[24830] DEBUG {'user-agent': 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/532.0 (KHTML, like Gecko) Chrome/4.0.211.4 Safari/532.0'}
2021-03-12 15:29:19 localhost anime_downloader.sites.helpers.request[24830] DEBUG -----
2021-03-12 15:29:19 localhost anime_downloader.session[24830] DEBUG cached request
2021-03-12 15:29:19 localhost anime_downloader.sites.helpers.request[24830] DEBUG https://check.ddos-guard.net/check.js
2021-03-12 15:29:19 localhost anime_downloader.sites.helpers.request[24830] DEBUG /data/data/com.termux/files/usr/tmp/animedl_w1kjv5x/tmp_93s0s0b
2021-03-12 15:29:19 localhost anime_downloader.sites.helpers.request[24830] DEBUG -----
2021-03-12 15:29:19 localhost anime_downloader.sites.helpers.request[24830] DEBUG GET https://erai-raws.info/.well-known/ddos-guard/id/PY7XwCm25eC3I9VB
2021-03-12 15:29:19 localhost anime_downloader.sites.helpers.request[24830] DEBUG {}
2021-03-12 15:29:19 localhost anime_downloader.sites.helpers.request[24830] DEBUG {'user-agent': 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/532.0 (KHTML, like Gecko) Chrome/4.0.211.4 Safari/532.0'}
2021-03-12 15:29:19 localhost anime_downloader.sites.helpers.request[24830] DEBUG -----
2021-03-12 15:29:19 localhost anime_downloader.session[24830] DEBUG cached request
2021-03-12 15:29:19 localhost anime_downloader.sites.helpers.request[24830] DEBUG https://erai-raws.info/.well-known/ddos-guard/id/PY7XwCm25eC3I9VB
2021-03-12 15:29:19 localhost anime_downloader.sites.helpers.request[24830] DEBUG /data/data/com.termux/files/usr/tmp/animedl_w1kjv5x/tmpp8dbtvlm
2021-03-12 15:29:19 localhost anime_downloader.sites.helpers.request[24830] DEBUG -----
2021-03-12 15:29:19 localhost anime_downloader.sites.helpers.request[24830] DEBUG GET https://erai-raws.info/anime-list/jaku-chara-tomozaki-kun
2021-03-12 15:29:19 localhost anime_downloader.sites.helpers.request[24830] DEBUG {'cookies': <RequestsCookieJar[Cookie(version=0, name='__ddg2', value='PY7XwCm25eC3I9VB', port=None, port_specified=False, domain='.erai-raws.info', domain_specified=True, domain_initial_dot=False, path='/', path_specified=True, secure=False, expires=1647098963, discard=False, comment=None, comment_url=None, rest={'HttpOnly': None}, rfc2109=False)]>}
2021-03-12 15:29:19 localhost anime_downloader.sites.helpers.request[24830] DEBUG {'user-agent': 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/532.0 (KHTML, like Gecko) Chrome/4.0.211.4 Safari/532.0'}
2021-03-12 15:29:19 localhost anime_downloader.sites.helpers.request[24830] DEBUG -----
2021-03-12 15:29:19 localhost anime_downloader.session[24830] DEBUG cached request
2021-03-12 15:29:19 localhost anime_downloader.sites.helpers.request[24830] DEBUG https://www.erai-raws.info/anime-list/jaku-chara-tomozaki-kun/
2021-03-12 15:29:19 localhost anime_downloader.sites.helpers.request[24830] DEBUG /data/data/com.termux/files/usr/tmp/animedl_w1kjv5x/tmpc_nbjc5_
2021-03-12 15:29:20 localhost anime_downloader.sites.helpers.request[24830] DEBUG -----
2021-03-12 15:29:20 localhost anime_downloader.sites.helpers.request[24830] DEBUG GET https://check.ddos-guard.net/check.js
2021-03-12 15:29:20 localhost anime_downloader.sites.helpers.request[24830] DEBUG {}
2021-03-12 15:29:20 localhost anime_downloader.sites.helpers.request[24830] DEBUG {'user-agent': 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/532.0 (KHTML, like Gecko) Chrome/4.0.211.4 Safari/532.0'}
2021-03-12 15:29:20 localhost anime_downloader.sites.helpers.request[24830] DEBUG -----
2021-03-12 15:29:20 localhost anime_downloader.session[24830] DEBUG cached request
2021-03-12 15:29:20 localhost anime_downloader.sites.helpers.request[24830] DEBUG https://check.ddos-guard.net/check.js
2021-03-12 15:29:20 localhost anime_downloader.sites.helpers.request[24830] DEBUG /data/data/com.termux/files/usr/tmp/animedl_w1kjv5x/tmp1tmjpaxz
2021-03-12 15:29:20 localhost anime_downloader.sites.helpers.request[24830] DEBUG -----
2021-03-12 15:29:20 localhost anime_downloader.sites.helpers.request[24830] DEBUG GET https://erai-raws.info/.well-known/ddos-guard/id/PY7XwCm25eC3I9VB
2021-03-12 15:29:20 localhost anime_downloader.sites.helpers.request[24830] DEBUG {}
2021-03-12 15:29:20 localhost anime_downloader.sites.helpers.request[24830] DEBUG {'user-agent': 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/532.0 (KHTML, like Gecko) Chrome/4.0.211.4 Safari/532.0'}
2021-03-12 15:29:20 localhost anime_downloader.sites.helpers.request[24830] DEBUG -----
2021-03-12 15:29:20 localhost anime_downloader.session[24830] DEBUG cached request
2021-03-12 15:29:20 localhost anime_downloader.sites.helpers.request[24830] DEBUG https://erai-raws.info/.well-known/ddos-guard/id/PY7XwCm25eC3I9VB
2021-03-12 15:29:20 localhost anime_downloader.sites.helpers.request[24830] DEBUG /data/data/com.termux/files/usr/tmp/animedl_w1kjv5x/tmp_3h_kfr7
2021-03-12 15:29:20 localhost anime_downloader.sites.helpers.request[24830] DEBUG -----
2021-03-12 15:29:20 localhost anime_downloader.sites.helpers.request[24830] DEBUG GET https://www.erai-ddl3.info/folder/ff8c0a3ba57bfb82ad2134a484e05051/Jaku-Chara_Tomozaki-kun
2021-03-12 15:29:20 localhost anime_downloader.sites.helpers.request[24830] DEBUG {'cookies': <RequestsCookieJar[Cookie(version=0, name='__ddg2', value='PY7XwCm25eC3I9VB', port=None, port_specified=False, domain='.erai-raws.info', domain_specified=True, domain_initial_dot=False, path='/', path_specified=True, secure=False, expires=1647098963, discard=False, comment=None, comment_url=None, rest={'HttpOnly': None}, rfc2109=False)]>}
2021-03-12 15:29:20 localhost anime_downloader.sites.helpers.request[24830] DEBUG {'user-agent': 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/532.0 (KHTML, like Gecko) Chrome/4.0.211.4 Safari/532.0'}
2021-03-12 15:29:20 localhost anime_downloader.sites.helpers.request[24830] DEBUG -----
2021-03-12 15:29:20 localhost anime_downloader.session[24830] DEBUG cached request
2021-03-12 15:29:20 localhost anime_downloader.sites.helpers.request[24830] DEBUG https://www.erai-ddl3.info/folder/ff8c0a3ba57bfb82ad2134a484e05051/Jaku-Chara_Tomozaki-kun
2021-03-12 15:29:20 localhost anime_downloader.sites.helpers.request[24830] DEBUG /data/data/com.termux/files/usr/tmp/animedl_w1kjv5x/tmpy560g99f
2021-03-12 15:29:20 localhost anime_downloader.sites.anime[24830] DEBUG EPISODE IDS: length: 0, ids: []
send: b'GET /check.js HTTP/1.1\r\nHost: check.ddos-guard.net\r\nuser-agent: Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/532.0 (KHTML, like Gecko) Chrome/4.0.211.4 Safari/532.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\n\r\n'
reply: 'HTTP/1.1 200 Ok\r\n'
header: Server: ddos-guard
header: Date: Fri, 12 Mar 2021 15:29:23 GMT
header: Connection: keep-alive
header: Keep-Alive: timeout=60
header: Content-Type: application/javascript
header: Expires: Sat, 12 Mar 2022 15:29:23 GMT
header: Last-Modified: Thu, 01 Jan 1970 00:00:00 GMT
header: Cache-Control: private, s-maxage=0, max-age=31536000
header: P3P: CP="IDC DSP COR ADM DEVi TAIi PSA PSD IVAi IVDi CONi HIS OUR IND CNT"
header: ETag: PY7XwCm25eC3I9VB
header: Set-Cookie: __ddg2=PY7XwCm25eC3I9VB; Domain=check.ddos-guard.net; Path=/; HttpOnly; SameSite=None; Secure; Expires=Sat, 12-Mar-2022 15:29:23 GMT
header: Content-Length: 152
send: b'GET /.well-known/ddos-guard/id/PY7XwCm25eC3I9VB HTTP/1.1\r\nHost: erai-raws.info\r\nuser-agent: Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/532.0 (KHTML, like Gecko) Chrome/4.0.211.4 Safari/532.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\n\r\n'
reply: 'HTTP/1.1 200 Ok\r\n'
header: Server: ddos-guard
header: Date: Fri, 12 Mar 2021 15:29:23 GMT
header: Connection: keep-alive
header: Keep-Alive: timeout=60
header: Content-Type: image/png
header: Expires: Thu, 01 Jan 1970 00:00:00 GMT
header: Cache-Control: no-cache
header: Set-Cookie: __ddg2=PY7XwCm25eC3I9VB; Domain=erai-raws.info; Path=/; HttpOnly; Expires=Sat, 12-Mar-2022 15:29:23 GMT
header: Content-Length: 68
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/anime", line 33, in <module>
    sys.exit(load_entry_point('anime-downloader', 'console_scripts', 'anime')())
  File "/data/data/com.termux/files/home/src/anime-downloader/anime_downloader/cli.py", line 53, in main
    cli()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/data/data/com.termux/files/home/src/anime-downloader/anime_downloader/commands/dl.py", line 101, in command
    anime = cls(anime_url, quality=quality,
  File "/data/data/com.termux/files/home/src/anime-downloader/anime_downloader/sites/anime.py", line 84, in __init__
    self._episode_urls = self.get_data()
  File "/data/data/com.termux/files/home/src/anime-downloader/anime_downloader/sites/anime.py", line 171, in get_data
    if not isinstance(self._episode_urls[0], tuple):
IndexError: list index out of range
```

**Comment by AbdullahM0hamed** [comment]
Will look into this myself in a few hours

**Comment by ArjixWasTaken** [comment]
wow, red guy must be an immortal if 2 years are just a few hours for him.

**Comment by AbdullahM0hamed** [comment]
I ain't even do it, I just didn't want open issues in my issues tab lol
