### ISSUE TITLE
[BUG] voiranime don't work

### ISSUE THREAD

**Issue by Oreo81** [anime-dl/anime-downloader#652]
**Describe the bug**

When i went donwload any anime from voiranime.com, it says to me "list index out of range"

**To reproduce**

```
anime dl https://voiranime.com/anime/kimagure-orange-road/ 
```

<details>
<summary>LOG</summary>

```
I:\>anime -ll DEBUG dl https://voiranime.com/anime/kimagure-orange-road/
2021-03-23 21:55:39 DESKTOP-5ET0IV6 anime_downloader.util[47400] INFO anime-downloader 5.0.7
2021-03-23 21:55:39 DESKTOP-5ET0IV6 anime_downloader.util[47400] DEBUG Platform: Windows-10-10.0.19041-SP0
2021-03-23 21:55:39 DESKTOP-5ET0IV6 anime_downloader.util[47400] DEBUG Python 3.9.2
2021-03-23 21:55:39 DESKTOP-5ET0IV6 anime_downloader.sites.anime[47400] INFO Extracting episode info from page
2021-03-23 21:55:39 DESKTOP-5ET0IV6 anime_downloader.sites.helpers.request[47400] DEBUG -----
2021-03-23 21:55:39 DESKTOP-5ET0IV6 anime_downloader.sites.helpers.request[47400] DEBUG GET https://voiranime.com/anime/kimagure-orange-road/
2021-03-23 21:55:39 DESKTOP-5ET0IV6 anime_downloader.sites.helpers.request[47400] DEBUG {}
2021-03-23 21:55:39 DESKTOP-5ET0IV6 anime_downloader.sites.helpers.request[47400] DEBUG {'user-agent': 'Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.66 Safari/535.11'}
2021-03-23 21:55:39 DESKTOP-5ET0IV6 anime_downloader.sites.helpers.request[47400] DEBUG -----
2021-03-23 21:55:39 DESKTOP-5ET0IV6 anime_downloader.session[47400] DEBUG cached request
2021-03-23 21:55:39 DESKTOP-5ET0IV6 anime_downloader.sites.helpers.request[47400] DEBUG https://voiranime.com/anime/kimagure-orange-road/
2021-03-23 21:55:39 DESKTOP-5ET0IV6 anime_downloader.sites.helpers.request[47400] DEBUG C:\Users\ADMINI~1\AppData\Local\Temp\animedl_2jjqw6_\tmppnkasiew
2021-03-23 21:55:40 DESKTOP-5ET0IV6 anime_downloader.sites.anime[47400] DEBUG Metadata scraping error: list index out of range
2021-03-23 21:55:40 DESKTOP-5ET0IV6 anime_downloader.sites.helpers.request[47400] DEBUG -----
2021-03-23 21:55:40 DESKTOP-5ET0IV6 anime_downloader.sites.helpers.request[47400] DEBUG GET https://voiranime.com/anime/kimagure-orange-road/
2021-03-23 21:55:40 DESKTOP-5ET0IV6 anime_downloader.sites.helpers.request[47400] DEBUG {}
2021-03-23 21:55:40 DESKTOP-5ET0IV6 anime_downloader.sites.helpers.request[47400] DEBUG {'user-agent': 'Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.66 Safari/535.11'}
2021-03-23 21:55:40 DESKTOP-5ET0IV6 anime_downloader.sites.helpers.request[47400] DEBUG -----
2021-03-23 21:55:40 DESKTOP-5ET0IV6 anime_downloader.session[47400] DEBUG cached request
2021-03-23 21:55:40 DESKTOP-5ET0IV6 anime_downloader.sites.helpers.request[47400] DEBUG https://voiranime.com/anime/kimagure-orange-road/
2021-03-23 21:55:40 DESKTOP-5ET0IV6 anime_downloader.sites.helpers.request[47400] DEBUG C:\Users\ADMINI~1\AppData\Local\Temp\animedl_2jjqw6_\tmpuaa2kj67
Traceback (most recent call last):
  File "C:\Python39\Scripts\anime-script.py", line 33, in <module>
    sys.exit(load_entry_point('anime-downloader==5.0.7', 'console_scripts', 'anime')())
  File "c:\python39\lib\site-packages\anime_downloader\cli.py", line 53, in main
    cli()
  File "c:\python39\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\python39\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\python39\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\python39\lib\site-packages\anime_downloader\commands\dl.py", line 101, in command
    anime = cls(anime_url, quality=quality,
  File "c:\python39\lib\site-packages\anime_downloader\sites\anime.py", line 84, in __init__
    self._episode_urls = self.get_data()
  File "c:\python39\lib\site-packages\anime_downloader\sites\anime.py", line 165, in get_data
    self._episode_urls = self._scrape_episodes()
  File "c:\python39\lib\site-packages\anime_downloader\sites\voiranime.py", line 28, in _scrape_episodes
    next_page = soup.select('a.ct-btn')[0].get('href')
IndexError: list index out of range


```

**Comment by ArjixGamer** [comment]
voiranime introduced google captcha
so it makes sense why it doesnt work

**Comment by ArjixGamer** [comment]
@AbdullahM0hamed can you close this issue?

**Comment by AbdullahM0hamed** [comment]
Closing as it the provider has been axed for the time being (near impossible, due to captcha)
