### ISSUE TITLE
HTTP Error 0: The maximum retry attempts reached

### ISSUE THREAD

**Issue by yuis-ice** [anime-dl/anime-downloader#662]
hi. I'm new to the app. I tried to download an anime eps and I got the error. here is the logs. thanks.

```
$ anime --log-level DEBUG dl 'assault lily'
2021-04-07 19:51:48 DESKTOP-UHU8FSH anime_downloader.util[14263] INFO anime-downloader 5.0.9
2021-04-07 19:51:49 DESKTOP-UHU8FSH anime_downloader.util[14263] DEBUG Platform: Linux-4.4.0-19041-Microsoft-x86_64-with-debian-buster-sid
2021-04-07 19:51:49 DESKTOP-UHU8FSH anime_downloader.util[14263] DEBUG Python 3.7.6
2021-04-07 19:51:49 DESKTOP-UHU8FSH anime_downloader.sites.helpers.request[14263] DEBUG -----
2021-04-07 19:51:49 DESKTOP-UHU8FSH anime_downloader.sites.helpers.request[14263] DEBUG GET https://twist.moe/api/anime
2021-04-07 19:51:49 DESKTOP-UHU8FSH anime_downloader.sites.helpers.request[14263] DEBUG {}      
2021-04-07 19:51:49 DESKTOP-UHU8FSH anime_downloader.sites.helpers.request[14263] DEBUG {'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.46 Safari/537.36', 'x-access-token': '0df14814b9e590a1f26d3071a4ed7974'}
2021-04-07 19:51:49 DESKTOP-UHU8FSH anime_downloader.sites.helpers.request[14263] DEBUG -----   
2021-04-07 19:51:49 DESKTOP-UHU8FSH anime_downloader.session[14263] DEBUG cached request
2021-04-07 19:51:49 DESKTOP-UHU8FSH anime_downloader.sites.helpers.request[14263] DEBUG https://api.twist.moe/api/anime
2021-04-07 19:51:49 DESKTOP-UHU8FSH anime_downloader.sites.helpers.request[14263] DEBUG /mnt/c/_tmp/animedl15sqhcdz/tmp3k0391xj
+--------+-------------------------------------------------------+--------+
|      5 | Hanasaku Iroha                                        |        |
|      4 | Allison to Lillia                                     |        |
|      3 | Date A Live                                           |        |
|      2 | Fate/kaleid liner Prisma☆Illya Movie: Sekka no Chikai |        |
|      1 | Assault Lily: Bouquet                                 |        |
|--------+-------------------------------------------------------+--------|
|   SlNo | Title                                                 | Meta   |
+--------+-------------------------------------------------------+--------+
Enter the anime no: [1]: 1
2021-04-07 19:51:54 DESKTOP-UHU8FSH anime_downloader.util[14263] INFO Selected Assault Lily: Bouquet
2021-04-07 19:51:54 DESKTOP-UHU8FSH anime_downloader.sites.anime[14263] INFO Extracting episode 
info from page
2021-04-07 19:51:54 DESKTOP-UHU8FSH anime_downloader.sites.helpers.request[14263] DEBUG -----   
2021-04-07 19:51:54 DESKTOP-UHU8FSH anime_downloader.sites.helpers.request[14263] DEBUG GET https://twist.moe/api/anime/assault-lily-bouquet/sources
2021-04-07 19:51:54 DESKTOP-UHU8FSH anime_downloader.sites.helpers.request[14263] DEBUG {}      
2021-04-07 19:51:54 DESKTOP-UHU8FSH anime_downloader.sites.helpers.request[14263] DEBUG {'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.46 Safari/537.36', 'x-access-token': '0df14814b9e590a1f26d3071a4ed7974'}
2021-04-07 19:51:54 DESKTOP-UHU8FSH anime_downloader.sites.helpers.request[14263] DEBUG -----   
2021-04-07 19:51:54 DESKTOP-UHU8FSH anime_downloader.session[14263] DEBUG cached request
2021-04-07 19:51:54 DESKTOP-UHU8FSH anime_downloader.sites.helpers.request[14263] DEBUG https://api.twist.moe/api/anime/assault-lily-bouquet/sources
2021-04-07 19:51:54 DESKTOP-UHU8FSH anime_downloader.sites.helpers.request[14263] DEBUG /mnt/c/_tmp/animedl15sqhcdz/tmpfx1uw_lo
2021-04-07 19:51:54 DESKTOP-UHU8FSH anime_downloader.commands.dl[14263] INFO Found anime: assault-lily-bouquet
INFO:anime_downloader.commands.dl:Found anime: assault-lily-bouquet
2021-04-07 19:51:54 DESKTOP-UHU8FSH anime_downloader.commands.dl[14263] INFO Downloading to /mnt/c/pg/animedl
INFO:anime_downloader.commands.dl:Downloading to /mnt/c/pg/animedl
2021-04-07 19:51:54 DESKTOP-UHU8FSH anime_downloader.sites.anime[14263] DEBUG Extracting stream 
info of id: https://cdn.twist.moe/anime/assaultlilybouquet/[Erai-raws] Assault Lily - Bouquet - 
01 [1080p].mp4
DEBUG:anime_downloader.sites.anime:Extracting stream info of id: https://cdn.twist.moe/anime/assaultlilybouquet/[Erai-raws] Assault Lily - Bouquet - 01 [1080p].mp4
2021-04-07 19:51:54 DESKTOP-UHU8FSH anime_downloader.sites.anime[14263] DEBUG Sources : [('no_extractor', 'https://cdn.twist.moe/anime/assaultlilybouquet/[Erai-raws] Assault Lily - Bouquet - 01 [1080p].mp4')]
DEBUG:anime_downloader.sites.anime:Sources : [('no_extractor', 'https://cdn.twist.moe/anime/assaultlilybouquet/[Erai-raws] Assault Lily - Bouquet - 01 [1080p].mp4')]
2021-04-07 19:51:54 DESKTOP-UHU8FSH anime_downloader.sites.anime[14263] INFO Downloading assault-lily-bouquet-1
INFO:anime_downloader.sites.anime:Downloading assault-lily-bouquet-1
2021-04-07 19:51:54 DESKTOP-UHU8FSH anime_downloader.downloader.base_downloader[14263] INFO ./assault-lily-bouquet/assault-lily-bouquet_1.mp4
INFO:anime_downloader.downloader.base_downloader:./assault-lily-bouquet/assault-lily-bouquet_1.mp4
send: b'GET /anime/assaultlilybouquet/%5BErai-raws%5D%20Assault%20Lily%20-%20Bouquet%20-%2001%20%5B1080p%5D.mp4 HTTP/1.1\r\nHost: cdn.twist.moe\r\nuser-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) Gecko/20100101Firefox/56.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nreferer: https://twist.moe/a/assault-lily-bouquet/1\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server: nginx
header: Date: Wed, 07 Apr 2021 10:51:55 GMT
header: Content-Type: video/mp4
header: Content-Length: 399253035
header: Connection: keep-alive
header: Last-Modified: Fri, 02 Oct 2020 14:03:14 GMT
header: ETag: "5f773322-17cc1e2b"
header: X-Proxy-Cache: HIT
header: X-Proxy-Serve: EU-CDN
header: X-N: 23
header: Accept-Ranges: bytes
send: b'GET /anime/assaultlilybouquet/%5BErai-raws%5D%20Assault%20Lily%20-%20Bouquet%20-%2001%20%5B1080p%5D.mp4 HTTP/1.1\r\nHost: cdn.twist.moe\r\nuser-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) Gecko/20100101Firefox/56.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nreferer: https://twist.moe/a/assault-lily-bouquet/1\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server: nginx
header: Date: Wed, 07 Apr 2021 10:51:56 GMT
header: Content-Type: video/mp4
header: Content-Length: 399253035
header: Connection: keep-alive
header: Last-Modified: Fri, 02 Oct 2020 14:03:14 GMT
header: ETag: "5f773322-17cc1e2b"
header: X-Proxy-Cache: HIT
header: X-Proxy-Serve: EU-CDN
header: X-N: 23
header: Accept-Ranges: bytes
send: b'GET /anime/assaultlilybouquet/%5BErai-raws%5D%20Assault%20Lily%20-%20Bouquet%20-%2001%20%5B1080p%5D.mp4 HTTP/1.1\r\nHost: cdn.twist.moe\r\nuser-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) Gecko/20100101Firefox/56.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nreferer: https://twist.moe/a/assault-lily-bouquet/1\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server: nginx
header: Date: Wed, 07 Apr 2021 10:51:57 GMT
header: Content-Type: video/mp4
header: Content-Length: 399253035
header: Connection: keep-alive
header: Last-Modified: Fri, 02 Oct 2020 14:03:14 GMT
header: ETag: "5f773322-17cc1e2b"
header: X-Proxy-Cache: HIT
header: X-Proxy-Serve: EU-CDN
header: X-N: 23
header: Accept-Ranges: bytes
send: b'GET /anime/assaultlilybouquet/%5BErai-raws%5D%20Assault%20Lily%20-%20Bouquet%20-%2001%20%5B1080p%5D.mp4 HTTP/1.1\r\nHost: cdn.twist.moe\r\nuser-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) Gecko/20100101Firefox/56.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nreferer: https://twist.moe/a/assault-lily-bouquet/1\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server: nginx
header: Date: Wed, 07 Apr 2021 10:51:58 GMT
header: Content-Type: video/mp4
header: Content-Length: 399253035
header: Connection: keep-alive
header: Last-Modified: Fri, 02 Oct 2020 14:03:14 GMT
header: ETag: "5f773322-17cc1e2b"
header: X-Proxy-Cache: HIT
header: X-Proxy-Serve: EU-CDN
header: X-N: 23
header: Accept-Ranges: bytes
send: b'GET /anime/assaultlilybouquet/%5BErai-raws%5D%20Assault%20Lily%20-%20Bouquet%20-%2001%20%5B1080p%5D.mp4 HTTP/1.1\r\nHost: cdn.twist.moe\r\nuser-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) Gecko/20100101Firefox/56.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nreferer: https://twist.moe/a/assault-lily-bouquet/1\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server: nginx
header: Date: Wed, 07 Apr 2021 10:51:59 GMT
header: Content-Type: video/mp4
header: Content-Length: 399253035
header: Connection: keep-alive
header: Last-Modified: Fri, 02 Oct 2020 14:03:14 GMT
header: ETag: "5f773322-17cc1e2b"
header: X-Proxy-Cache: HIT
header: X-Proxy-Serve: EU-CDN
header: X-N: 23
header: Accept-Ranges: bytes
2021-04-07 19:51:59 DESKTOP-UHU8FSH anime_downloader.downloader.base_downloader[14263] DEBUG Total size: 399253035
DEBUG:anime_downloader.downloader.base_downloader:Total size: 399253035
 [*] 380.8 MB / 380.8 MB @ 168 kB/s [##################] [100%, 0s left]       
 [*] 380.8 MB / 380.8 MB @ 27 kB/s [##################] [100%, 0s left]    t]    
 [*] 380.8 MB / 380.8 MB @ 125 kB/s [##################] [100%, 0s left]        
 [*] 380.8 MB / 380.8 MB @ 48 kB/s [##################] [100%, 0s left]       
Traceback (most recent call last):
  File "/home/yuis/.pyenv/versions/3.7.6/bin/anime", line 8, in <module>
    sys.exit(main())
  File "/home/yuis/.pyenv/versions/3.7.6/lib/python3.7/site-packages/anime_downloader/cli.py", line 53, in main
    cli()
  File "/home/yuis/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/yuis/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/yuis/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/core.py", line 1259, 
in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/yuis/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/core.py", line 1066, 
in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yuis/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/yuis/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/decorators.py", line 
21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/yuis/.pyenv/versions/3.7.6/lib/python3.7/site-packages/anime_downloader/commands/dl.py", line 170, in command
    range_size=chunk_size)
  File "/home/yuis/.pyenv/versions/3.7.6/lib/python3.7/site-packages/anime_downloader/sites/anime.py", line 436, in download
    downloader.download()
  File "/home/yuis/.pyenv/versions/3.7.6/lib/python3.7/site-packages/anime_downloader/downloader/base_downloader.py", line 73, in download
    self._download()
  File "/home/yuis/.pyenv/versions/3.7.6/lib/python3.7/site-packages/anime_downloader/downloader/SmartDL.py", line 29, in _download
    obj.start()
  File "/home/yuis/.pyenv/versions/3.7.6/lib/python3.7/site-packages/pySmartDL/pySmartDL.py", line 329, in start
    self.wait(raise_exceptions=True)
  File "/home/yuis/.pyenv/versions/3.7.6/lib/python3.7/site-packages/pySmartDL/pySmartDL.py", line 488, in wait
    raise self.errors[-1]
urllib.error.HTTPError: HTTP Error 0: The maximum retry attempts reached (Diff between downloaded files and expected filesizes is 2977836B (filesize: 399253035, expected_filesize: 396275199.0, 1 threads).)
```

**Comment by yuis-ice** [comment]
It was on Windows WSL bash, I just tried with the Windows choco way and could download them successfully, so probably the error because it was WSL. You can close this issue if you want.
