### ISSUE TITLE
AnimeRush scrapes non-existent episodes

### ISSUE THREAD

**Issue by garbled1** [anime-dl/anime-downloader#697]
**Describe the bug**
I can't seem to get episode ranges of start with no end working anymore, example:

This shows 37 and 38:

/usr/local/bin/anime dl  --provider animerush 'daibou' --download-dir /video/TV/Anime/Dragon_Quest_-_The_Adventure_of_Dai/ -ff "{anime_title}_{ep_no}" -e 37:38 -u
anime: Selected Dragon Quest: Dai no Daibouken (2020)
anime: Extracting episode info from page
anime: Found anime: Dragon Quest: Dai no Daibouken (2020)
https://www13.mp4upload.com:282/d/q2x2zpolz3b4quuojoxuyycukf4d4qkin5undhm2i4aegmnsw344hmqh/video.mp4
https://www3.mp4upload.com:282/d/r2xuayoiz3b4quuojcxrizkjizxjdadnnz7ar22oqng725kl3zmz57hf/video.mp4

However:

/usr/local/bin/anime dl  --provider animerush 'daibou' --download-dir /video/TV/Anime/Dragon_Quest_-_The_Adventure_of_Dai/ -ff "{anime_title}_{ep_no}" -e 37:     

anime: Selected Dragon Quest: Dai no Daibouken (2020)
anime: Extracting episode info from page
anime: Found anime: Dragon Quest: Dai no Daibouken (2020)
ERROR: Invalid URL 'https:////www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2FAnimeRushNetwork&width=230&height=62&show_faces=false&colorscheme=dark&stream=false&show_border=false&header=false': No host supplied

**To reproduce**

```
/usr/local/bin/anime dl  --provider animerush 'daibou' --download-dir /video/TV/Anime/Dragon_Quest_-_The_Adventure_of_Dai/ -ff "{anime_title}_{ep_no}" -e 37:     
```

<details>
<summary>LOG</summary>

```
Enter the anime no: [1]: 3
2021-06-30 06:19:33 rotanev anime_downloader.util[6296] INFO Selected Dragon Quest: Dai no Daibouken (2020)
2021-06-30 06:19:33 rotanev anime_downloader.sites.anime[6296] INFO Extracting episode info from page
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG -----
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG GET https://www.animerush.tv/anime/Dragon-Quest-Dai-no-Daibouken-2020/
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG {}
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36'}
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG -----
2021-06-30 06:19:33 rotanev anime_downloader.session[6296] DEBUG cached request
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG https://www.animerush.tv/anime/Dragon-Quest-Dai-no-Daibouken-2020/
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG /tmp/animedlp0o0bt0j/tmp6fpqvbu2
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG -----
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG GET https://www.animerush.tv/anime/Dragon-Quest-Dai-no-Daibouken-2020/
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG {}
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36'}
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG -----
2021-06-30 06:19:33 rotanev anime_downloader.session[6296] DEBUG cached request
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG https://www.animerush.tv/anime/Dragon-Quest-Dai-no-Daibouken-2020/
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG /tmp/animedlp0o0bt0j/tmpjk08ynxe
2021-06-30 06:19:33 rotanev anime_downloader.sites.anime[6296] DEBUG EPISODE IDS: length: 39, ids: ['https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-1/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-2/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-3/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-4/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-5/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-6/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-7/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-8/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-9/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-10/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-11/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-12/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-13/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-14/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-15/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-16/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-17/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-18/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-19/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-20/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-21/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-22/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-23/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-24/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-25/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-26/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-27/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-28/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-29/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-30/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-31/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-32/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-33/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-34/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-35/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-36/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-37.5/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-37/', 'https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-38/']
2021-06-30 06:19:33 rotanev anime_downloader.commands.dl[6296] INFO Found anime: Dragon Quest: Dai no Daibouken (2020)
2021-06-30 06:19:33 rotanev anime_downloader.sites.anime[6296] DEBUG Extracting stream info of id: https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-37.5/
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG -----
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG GET https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-37.5/
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG {}
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36'}
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG -----
2021-06-30 06:19:33 rotanev anime_downloader.session[6296] DEBUG cached request
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-37.5/
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG /tmp/animedlp0o0bt0j/tmpb2oc_mb0
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG -----
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG GET https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-37.5/mirror-448518/
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG {}
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36'}
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG -----
2021-06-30 06:19:33 rotanev anime_downloader.session[6296] DEBUG cached request
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-37.5/mirror-448518/
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG /tmp/animedlp0o0bt0j/tmpkw6hj_9e
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG -----
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG GET https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-37.5/mirror-448519/
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG {}
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36'}
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG -----
2021-06-30 06:19:33 rotanev anime_downloader.session[6296] DEBUG cached request
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-37.5/mirror-448519/
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG /tmp/animedlp0o0bt0j/tmp38oq_2ek
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG -----
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG GET https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-37.5/
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG {}
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36'}
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG -----
2021-06-30 06:19:33 rotanev anime_downloader.session[6296] DEBUG cached request
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-37.5/
2021-06-30 06:19:33 rotanev anime_downloader.sites.helpers.request[6296] DEBUG /tmp/animedlp0o0bt0j/tmpfhva35qz
2021-06-30 06:19:34 rotanev anime_downloader.sites.animerush[6296] DEBUG Sources: [['https://mp4upload.com/embed-2ysdr9liof49-650x370.html', 'Mp4uploadHD Video'], ['https://yourupload.com/embed/yk5Cdi56BhXr', 'Youruploads Video'], ['https://mp4upload.com/embed-sbsxsbgc3r7m-650x370.html', 'MP4Upload']]
2021-06-30 06:19:34 rotanev anime_downloader.sites.anime[6296] DEBUG Data : [{'extractor': 'mp4upload', 'url': 'https://mp4upload.com/embed-2ysdr9liof49-650x370.html', 'server': 'Mp4uploadHD Video', 'version': 'subbed'}, {'extractor': 'yourupload', 'url': 'https://yourupload.com/embed/yk5Cdi56BhXr', 'server': 'Youruploads Video', 'version': 'subbed'}, {'extractor': 'mp4upload', 'url': 'https://mp4upload.com/embed-sbsxsbgc3r7m-650x370.html', 'server': 'MP4Upload', 'version': 'subbed'}]
2021-06-30 06:19:34 rotanev anime_downloader.sites.anime[6296] DEBUG Sorted sources : [{'extractor': 'mp4upload', 'url': 'https://mp4upload.com/embed-2ysdr9liof49-650x370.html', 'server': 'Mp4uploadHD Video', 'version': 'subbed'}, {'extractor': 'mp4upload', 'url': 'https://mp4upload.com/embed-sbsxsbgc3r7m-650x370.html', 'server': 'MP4Upload', 'version': 'subbed'}, {'extractor': 'yourupload', 'url': 'https://yourupload.com/embed/yk5Cdi56BhXr', 'server': 'Youruploads Video', 'version': 'subbed'}]
2021-06-30 06:19:34 rotanev anime_downloader.sites.anime[6296] DEBUG Sources : [('mp4upload', 'https://mp4upload.com/embed-2ysdr9liof49-650x370.html')]
2021-06-30 06:19:34 rotanev anime_downloader.sites.helpers.request[6296] DEBUG -----
2021-06-30 06:19:34 rotanev anime_downloader.sites.helpers.request[6296] DEBUG GET https://mp4upload.com/embed-2ysdr9liof49-650x370.html
2021-06-30 06:19:34 rotanev anime_downloader.sites.helpers.request[6296] DEBUG {}
2021-06-30 06:19:34 rotanev anime_downloader.sites.helpers.request[6296] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36'}
2021-06-30 06:19:34 rotanev anime_downloader.sites.helpers.request[6296] DEBUG -----
2021-06-30 06:19:34 rotanev anime_downloader.session[6296] DEBUG cached request
2021-06-30 06:19:34 rotanev anime_downloader.sites.helpers.request[6296] DEBUG https://www.mp4upload.com/embed-2ysdr9liof49-650x370.html
2021-06-30 06:19:34 rotanev anime_downloader.sites.helpers.request[6296] DEBUG /tmp/animedlp0o0bt0j/tmpkva0bm66
2021-06-30 06:19:35 rotanev anime_downloader.sites.anime[6296] DEBUG Extracting stream info of id: https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-37/
2021-06-30 06:19:35 rotanev anime_downloader.sites.helpers.request[6296] DEBUG -----
2021-06-30 06:19:35 rotanev anime_downloader.sites.helpers.request[6296] DEBUG GET https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-37/
2021-06-30 06:19:35 rotanev anime_downloader.sites.helpers.request[6296] DEBUG {}
2021-06-30 06:19:35 rotanev anime_downloader.sites.helpers.request[6296] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36'}
2021-06-30 06:19:35 rotanev anime_downloader.sites.helpers.request[6296] DEBUG -----
2021-06-30 06:19:35 rotanev anime_downloader.session[6296] DEBUG cached request
2021-06-30 06:19:35 rotanev anime_downloader.sites.helpers.request[6296] DEBUG https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-37/
2021-06-30 06:19:35 rotanev anime_downloader.sites.helpers.request[6296] DEBUG /tmp/animedlp0o0bt0j/tmpu9rl4917
2021-06-30 06:19:35 rotanev anime_downloader.sites.helpers.request[6296] DEBUG -----
2021-06-30 06:19:35 rotanev anime_downloader.sites.helpers.request[6296] DEBUG GET https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-37/mirror-447535/
2021-06-30 06:19:35 rotanev anime_downloader.sites.helpers.request[6296] DEBUG {}
2021-06-30 06:19:35 rotanev anime_downloader.sites.helpers.request[6296] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36'}
2021-06-30 06:19:35 rotanev anime_downloader.sites.helpers.request[6296] DEBUG -----
2021-06-30 06:19:35 rotanev anime_downloader.session[6296] DEBUG cached request
2021-06-30 06:19:35 rotanev anime_downloader.sites.helpers.request[6296] DEBUG https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-37/mirror-447535/
2021-06-30 06:19:35 rotanev anime_downloader.sites.helpers.request[6296] DEBUG /tmp/animedlp0o0bt0j/tmpctetz1r_
2021-06-30 06:19:35 rotanev anime_downloader.sites.helpers.request[6296] DEBUG -----
2021-06-30 06:19:35 rotanev anime_downloader.sites.helpers.request[6296] DEBUG GET https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-37/mirror-447536/
2021-06-30 06:19:35 rotanev anime_downloader.sites.helpers.request[6296] DEBUG {}
2021-06-30 06:19:35 rotanev anime_downloader.sites.helpers.request[6296] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36'}
2021-06-30 06:19:35 rotanev anime_downloader.sites.helpers.request[6296] DEBUG -----
2021-06-30 06:19:35 rotanev anime_downloader.session[6296] DEBUG cached request
2021-06-30 06:19:35 rotanev anime_downloader.sites.helpers.request[6296] DEBUG https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-37/mirror-447536/
2021-06-30 06:19:35 rotanev anime_downloader.sites.helpers.request[6296] DEBUG /tmp/animedlp0o0bt0j/tmprq8cfsp3
2021-06-30 06:19:35 rotanev anime_downloader.sites.helpers.request[6296] DEBUG -----
2021-06-30 06:19:35 rotanev anime_downloader.sites.helpers.request[6296] DEBUG GET https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-37/
2021-06-30 06:19:35 rotanev anime_downloader.sites.helpers.request[6296] DEBUG {}
2021-06-30 06:19:35 rotanev anime_downloader.sites.helpers.request[6296] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36'}
2021-06-30 06:19:35 rotanev anime_downloader.sites.helpers.request[6296] DEBUG -----
2021-06-30 06:19:35 rotanev anime_downloader.session[6296] DEBUG cached request
2021-06-30 06:19:35 rotanev anime_downloader.sites.helpers.request[6296] DEBUG https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-37/
2021-06-30 06:19:35 rotanev anime_downloader.sites.helpers.request[6296] DEBUG /tmp/animedlp0o0bt0j/tmpvz77xptx
2021-06-30 06:19:35 rotanev anime_downloader.sites.animerush[6296] DEBUG Sources: [['https://mp4upload.com/embed-rfoz4yq492mq-650x370.html', 'Mp4uploadHD Video'], ['https://yourupload.com/embed/0VF2eN3rxW6B', 'Youruploads Video'], ['https://mp4upload.com/embed-7at9l0c8ammw-650x370.html', 'MP4Upload']]
2021-06-30 06:19:35 rotanev anime_downloader.sites.anime[6296] DEBUG Data : [{'extractor': 'mp4upload', 'url': 'https://mp4upload.com/embed-rfoz4yq492mq-650x370.html', 'server': 'Mp4uploadHD Video', 'version': 'subbed'}, {'extractor': 'yourupload', 'url': 'https://yourupload.com/embed/0VF2eN3rxW6B', 'server': 'Youruploads Video', 'version': 'subbed'}, {'extractor': 'mp4upload', 'url': 'https://mp4upload.com/embed-7at9l0c8ammw-650x370.html', 'server': 'MP4Upload', 'version': 'subbed'}]
2021-06-30 06:19:35 rotanev anime_downloader.sites.anime[6296] DEBUG Sorted sources : [{'extractor': 'mp4upload', 'url': 'https://mp4upload.com/embed-rfoz4yq492mq-650x370.html', 'server': 'Mp4uploadHD Video', 'version': 'subbed'}, {'extractor': 'mp4upload', 'url': 'https://mp4upload.com/embed-7at9l0c8ammw-650x370.html', 'server': 'MP4Upload', 'version': 'subbed'}, {'extractor': 'yourupload', 'url': 'https://yourupload.com/embed/0VF2eN3rxW6B', 'server': 'Youruploads Video', 'version': 'subbed'}]
2021-06-30 06:19:35 rotanev anime_downloader.sites.anime[6296] DEBUG Sources : [('mp4upload', 'https://mp4upload.com/embed-rfoz4yq492mq-650x370.html')]
2021-06-30 06:19:35 rotanev anime_downloader.sites.helpers.request[6296] DEBUG -----
2021-06-30 06:19:35 rotanev anime_downloader.sites.helpers.request[6296] DEBUG GET https://mp4upload.com/embed-rfoz4yq492mq-650x370.html
2021-06-30 06:19:35 rotanev anime_downloader.sites.helpers.request[6296] DEBUG {}
2021-06-30 06:19:35 rotanev anime_downloader.sites.helpers.request[6296] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36'}
2021-06-30 06:19:35 rotanev anime_downloader.sites.helpers.request[6296] DEBUG -----
2021-06-30 06:19:35 rotanev anime_downloader.session[6296] DEBUG cached request
2021-06-30 06:19:35 rotanev anime_downloader.sites.helpers.request[6296] DEBUG https://www.mp4upload.com/embed-rfoz4yq492mq-650x370.html
2021-06-30 06:19:35 rotanev anime_downloader.sites.helpers.request[6296] DEBUG /tmp/animedlp0o0bt0j/tmpy6m8zung
2021-06-30 06:19:36 rotanev anime_downloader.sites.anime[6296] DEBUG Extracting stream info of id: https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-38/
2021-06-30 06:19:36 rotanev anime_downloader.sites.helpers.request[6296] DEBUG -----
2021-06-30 06:19:36 rotanev anime_downloader.sites.helpers.request[6296] DEBUG GET https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-38/
2021-06-30 06:19:36 rotanev anime_downloader.sites.helpers.request[6296] DEBUG {}
2021-06-30 06:19:36 rotanev anime_downloader.sites.helpers.request[6296] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36'}
2021-06-30 06:19:36 rotanev anime_downloader.sites.helpers.request[6296] DEBUG -----
2021-06-30 06:19:36 rotanev anime_downloader.session[6296] DEBUG cached request
2021-06-30 06:19:36 rotanev anime_downloader.sites.helpers.request[6296] DEBUG https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-38/
2021-06-30 06:19:36 rotanev anime_downloader.sites.helpers.request[6296] DEBUG /tmp/animedlp0o0bt0j/tmp0bvw6hpm
2021-06-30 06:19:36 rotanev anime_downloader.sites.helpers.request[6296] DEBUG -----
2021-06-30 06:19:36 rotanev anime_downloader.sites.helpers.request[6296] DEBUG GET https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-38/
2021-06-30 06:19:36 rotanev anime_downloader.sites.helpers.request[6296] DEBUG {}
2021-06-30 06:19:36 rotanev anime_downloader.sites.helpers.request[6296] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36'}
2021-06-30 06:19:36 rotanev anime_downloader.sites.helpers.request[6296] DEBUG -----
2021-06-30 06:19:36 rotanev anime_downloader.session[6296] DEBUG cached request
2021-06-30 06:19:36 rotanev anime_downloader.sites.helpers.request[6296] DEBUG https://www.animerush.tv/Dragon-Quest-Dai-no-Daibouken-2020-episode-38/
2021-06-30 06:19:36 rotanev anime_downloader.sites.helpers.request[6296] DEBUG /tmp/animedlp0o0bt0j/tmpgcwbcszm
2021-06-30 06:19:36 rotanev anime_downloader.sites.animerush[6296] DEBUG Sources: [['//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2FAnimeRushNetwork&width=230&height=62&show_faces=false&colorscheme=dark&stream=false&show_border=false&header=false', None]]
2021-06-30 06:19:36 rotanev anime_downloader.sites.anime[6296] DEBUG Data : [{'extractor': 'mp4upload', 'url': '//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2FAnimeRushNetwork&width=230&height=62&show_faces=false&colorscheme=dark&stream=false&show_border=false&header=false', 'server': None, 'version': 'subbed'}]
2021-06-30 06:19:36 rotanev anime_downloader.sites.anime[6296] DEBUG Sorted sources : [{'extractor': 'mp4upload', 'url': '//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2FAnimeRushNetwork&width=230&height=62&show_faces=false&colorscheme=dark&stream=false&show_border=false&header=false', 'server': None, 'version': 'subbed'}]
2021-06-30 06:19:36 rotanev anime_downloader.sites.anime[6296] DEBUG Sources : [('mp4upload', '//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2FAnimeRushNetwork&width=230&height=62&show_faces=false&colorscheme=dark&stream=false&show_border=false&header=false')]
2021-06-30 06:19:36 rotanev anime_downloader.sites.helpers.request[6296] DEBUG -----
2021-06-30 06:19:36 rotanev anime_downloader.sites.helpers.request[6296] DEBUG GET https:////www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2FAnimeRushNetwork&width=230&height=62&show_faces=false&colorscheme=dark&stream=false&show_border=false&header=false
2021-06-30 06:19:36 rotanev anime_downloader.sites.helpers.request[6296] DEBUG {}
2021-06-30 06:19:36 rotanev anime_downloader.sites.helpers.request[6296] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36'}
2021-06-30 06:19:36 rotanev anime_downloader.sites.helpers.request[6296] DEBUG -----
Traceback (most recent call last):
  File "/usr/local/bin/anime", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/anime_downloader/cli.py", line 53, in main
    cli()
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/anime_downloader/commands/dl.py", line 122, in command
    animes = util.parse_ep_str(anime, episode_range)
  File "/usr/local/lib/python3.7/dist-packages/anime_downloader/util.py", line 205, in parse_ep_str
    for episode in split_anime(anime, episode_grammar):
  File "/usr/local/lib/python3.7/dist-packages/anime_downloader/sites/anime.py", line 201, in __iter__
    yield episode_class(ep_id[1], parent=self, ep_no=ep_id[0])
  File "/usr/local/lib/python3.7/dist-packages/anime_downloader/sites/anime.py", line 298, in __init__
    try_data()
  File "/usr/local/lib/python3.7/dist-packages/anime_downloader/sites/anime.py", line 296, in try_data
    self.source().stream_url
  File "/usr/local/lib/python3.7/dist-packages/anime_downloader/extractors/base_extractor.py", line 32, in stream_url
    self.get_data()
  File "/usr/local/lib/python3.7/dist-packages/anime_downloader/extractors/base_extractor.py", line 44, in get_data
    data = self._get_data()
  File "/usr/local/lib/python3.7/dist-packages/anime_downloader/extractors/mp4upload.py", line 13, in _get_data
    soup = str(helpers.get(self.url).text)
  File "/usr/local/lib/python3.7/dist-packages/anime_downloader/sites/helpers/request.py", line 80, in setup_func
    **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests_cache/core.py", line 136, in request
    **kwargs
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python3/dist-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 390, in prepare_url
    raise InvalidURL("Invalid URL %r: No host supplied" % url)
requests.exceptions.InvalidURL: Invalid URL 'https:////www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2FAnimeRushNetwork&width=230&height=62&show_faces=false&colorscheme=dark&stream=false&show_border=false&header=false': No host supplied



```

**Comment by ArjixWasTaken** [comment]
Um....no, this is not the case at all.
Episode 39 just doesnt work.
