### ISSUE TITLE
SmartDL.__init__() got an unexpected keyword argument 'verify'

### ISSUE THREAD

**Issue by FilippoMutta** [anime-dl/anime-downloader#726]
**Description**
I was running anime-downloader to download ad anime and it crashed. It found the anime just fine, but when it tried downloading got a python library error: "SmartDL.__init__() got an unexpected keyword argument 'verify'"

**To reproduce**
```
anime dl -e 1:24 -s https://www.anitube.site/62280/
```
<details>
<summary>LOG</summary>

```
Traceback (most recent call last):
  File "/usr/bin/anime", line 33, in <module>
    sys.exit(load_entry_point('anime-downloader==5.0.17', 'console_scripts', 'anime')())
  File "/usr/lib/python3.10/site-packages/anime_downloader/cli.py", line 81, in main
    cli()
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/anime_downloader/commands/dl.py", line 178, in command
    episode.download(force=force_download,
  File "/usr/lib/python3.10/site-packages/anime_downloader/sites/anime.py", line 436, in download
    downloader.download()
  File "/usr/lib/python3.10/site-packages/anime_downloader/downloader/base_downloader.py", line 73, in download
    self._download()
  File "/usr/lib/python3.10/site-packages/anime_downloader/downloader/SmartDL.py", line 28, in _download
    obj = SmartDL(url, dest, request_args=request_args, progress_bar=True, verify=False)
TypeError: SmartDL.__init__() got an unexpected keyword argument 'ver

```

**Comment by ArjixWasTaken** [comment]
ah yes, SmartDL making breaking changes
how nice

@FilippoMutta change the external downloader to aria2
It's the best option.

make sure you have aria2 installed
and either add `{aria2}` as the external downloader in the config
or use `-xd {aria2}` whenever you run the command

**Comment by FilippoMutta** [comment]
> ah yes, SmartDL making breaking changes how nice
Love it.
Thanks, with aria2 it works.

**Comment by ArjixWasTaken** [comment]
nice
