### ISSUE TITLE
Python TypeError when trying to download anything

### ISSUE THREAD

**Issue by V01D-NULL** [anime-dl/anime-downloader#742]
**Describe the bug**
`TypeError: string indices must be integers` when trying to download an anime.
These errors appear for any provider I tried, but I will be showcasing `wcostream` for this bug report as I'm not sure if different services cause different errors, and I'm likely to stick with wcostream anyway.

**To reproduce**
```
$ anime gui
  search bar: Boruto
  provider: wcostream
  Click the search button
  select anything (In my case it was Boruto: Naruto next generations (Dub))
  Click the download button
  Wait a few seconds...error.
```

<details>
<summary>

```
$ anime --log-level DEBUG gui
2022-07-23 19:24:51 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG -----
2022-07-23 19:24:51 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG GET https://wcostream.cc/search
2022-07-23 19:24:51 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG {'params': {'keyword': 'boruto'}}
2022-07-23 19:24:51 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG {'user-agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/604.2.1 (KHTML, like Gecko) Chrome/90.0.4421.100 Safari/604.2.1'}
2022-07-23 19:24:51 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG -----
2022-07-23 19:24:51 tim-Satellite-E45-B anime_downloader.session[108243] DEBUG cached request
2022-07-23 19:24:51 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG https://wcostream.cc/search?keyword=boruto
2022-07-23 19:24:51 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG /tmp/animedl43bd6ao5/tmp0veolll9
boruto wcostream 7
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG -----
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG GET https://wcostream.cc/search
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG {'params': {'keyword': 'boruto'}}
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG {'user-agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/604.2.1 (KHTML, like Gecko) Chrome/90.0.4421.100 Safari/604.2.1'}
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG -----
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.session[108243] DEBUG cached request
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG https://wcostream.cc/search?keyword=boruto
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG /tmp/animedl43bd6ao5/tmpdmubiifs
+--------+---------------------------------------------------------------+--------+
|      8 | Boruto: Jump Festa 2016 Special (Dub)                         |   2016 |
|      7 | Boruto: Naruto Next Generations (Dub)                         |   2017 |
|      6 | Boruto: Jump Festa 2016 Special                               |   2016 |
|      5 | Boruto: Naruto the Movie - The Day Naruto Became Hokage (Dub) |   2016 |
|      4 | Boruto: Naruto the Movie (Dub)                                |   2015 |
|      3 | Boruto: Naruto Next Generations                               |   2017 |
|      2 | Boruto: Naruto the Movie - The Day Naruto Became Hokage       |   2016 |
|      1 | Boruto: Naruto the Movie                                      |   2015 |
|--------+---------------------------------------------------------------+--------|
|   SlNo | Title                                                         |   Meta |
+--------+---------------------------------------------------------------+--------+
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.util[108243] INFO Selected Boruto: Naruto Next Generations (Dub)
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.anime[108243] INFO Extracting episode info from page
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG -----
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG GET https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-155/
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG {}
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG {'user-agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/604.2.1 (KHTML, like Gecko) Chrome/90.0.4421.100 Safari/604.2.1'}
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG -----
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.session[108243] DEBUG cached request
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-155/
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG /tmp/animedl43bd6ao5/tmpyodcai14
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG -----
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG GET https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-155/
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG {}
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG {'user-agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/604.2.1 (KHTML, like Gecko) Chrome/90.0.4421.100 Safari/604.2.1'}
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG -----
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.session[108243] DEBUG cached request
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-155/
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG /tmp/animedl43bd6ao5/tmpfohsd0wi
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.anime[108243] DEBUG EPISODE IDS: length: 155, ids: ['https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-1/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-2/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-3/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-4/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-5/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-6/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-7/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-8/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-9/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-10/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-11/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-12/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-13/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-14/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-15/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-16/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-17/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-18/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-19/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-20/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-21/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-22/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-23/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-24/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-25/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-26/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-27/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-28/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-29/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-30/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-31/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-32/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-33/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-34/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-35/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-36/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-37/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-38/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-39/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-40/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-41/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-42/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-43/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-44/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-45/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-46/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-47/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-48/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-49/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-50/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-51/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-52/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-53/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-54/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-55/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-56/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-57/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-58/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-59/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-60/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-61/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-62/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-63/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-64/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-65/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-66/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-67/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-68/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-69/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-70/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-71/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-72/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-73/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-74/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-75/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-76/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-77/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-78/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-79/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-80/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-81/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-82/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-83/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-84/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-85/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-86/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-87/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-88/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-89/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-90/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-91/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-92/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-93/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-94/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-95/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-96/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-97/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-98/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-99/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-100/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-101/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-102/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-103/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-104/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-105/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-106/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-107/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-108/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-109/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-110/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-111/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-112/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-113/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-114/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-115/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-116/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-117/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-118/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-119/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-120/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-121/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-122/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-123/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-124/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-125/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-126/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-127/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-128/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-129/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-130/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-131/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-132/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-133/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-134/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-135/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-136/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-137/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-138/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-139/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-140/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-141/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-142/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-143/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-144/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-145/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-146/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-147/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-148/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-149/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-150/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-151/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-152/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-153/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-154/', 'https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-155/']
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.anime[108243] DEBUG Extracting stream info of id: https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-1/
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG -----
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG GET https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-1/
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG {}
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG {'user-agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/604.2.1 (KHTML, like Gecko) Chrome/90.0.4421.100 Safari/604.2.1'}
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG -----
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.session[108243] DEBUG cached request
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG https://wcostream.cc/watch/boruto-naruto-next-generations-dub-VnkY-episode-1/
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG /tmp/animedl43bd6ao5/tmpmqyu_j5u
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG -----
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG GET https://vidstream.pro/e/RLJQMX5N7P59?domain=wcostream.cc
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG {}
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG {'user-agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/604.2.1 (KHTML, like Gecko) Chrome/90.0.4421.100 Safari/604.2.1', 'referer': 'https://wcostream.cc/'}
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG -----
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.session[108243] DEBUG cached request
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG https://vizcloud.site/e/RLJQMX5N7P59?domain=wcostream.cc
2022-07-23 19:25:06 tim-Satellite-E45-B anime_downloader.sites.helpers.request[108243] DEBUG /tmp/animedl43bd6ao5/tmpwlsp32q5

Traceback (most recent call last):
  File "/home/tim/.local/lib/python3.8/site-packages/anime_downloader/gui.py", line 25, in run
    self.fn(*self.args, **self.kwargs, signal=self.signal)
  File "/home/tim/.local/lib/python3.8/site-packages/anime_downloader/gui.py", line 235, in download_episodes
    for count, episode in enumerate(animes, 1):
  File "/home/tim/.local/lib/python3.8/site-packages/anime_downloader/sites/anime.py", line 201, in __iter__
    yield episode_class(ep_id[1], parent=self, ep_no=ep_id[0])
  File "/home/tim/.local/lib/python3.8/site-packages/anime_downloader/sites/anime.py", line 298, in __init__
    try_data()
  File "/home/tim/.local/lib/python3.8/site-packages/anime_downloader/sites/anime.py", line 294, in try_data
    self.get_data()
  File "/home/tim/.local/lib/python3.8/site-packages/anime_downloader/sites/anime.py", line 355, in get_data
    self._sources = self._get_sources()
  File "/home/tim/.local/lib/python3.8/site-packages/anime_downloader/sites/wcostream.py", line 69, in _get_sources
    sources.extend([('no_extractor', x['stream_url']) for x in ext._get_data()])  # noqa
  File "/home/tim/.local/lib/python3.8/site-packages/anime_downloader/sites/wcostream.py", line 69, in <listcomp>
    sources.extend([('no_extractor', x['stream_url']) for x in ext._get_data()])  # noqa
TypeError: string indices must be integers
```
</summary>

```



```

**Comment by Fantasy-Boss** [comment]
**https://github.com/Fantasy-Boss/9anime-Downloader**

### ***9anime Downloader***
**Features:**
1. Download Whole Season with One click.
2. Download options: Sub - Dub - Video Quality.
3. Fully Free, no Ads, no Virus, 100% Safe.
4. Scrapping with progress bar.
5. One click IDM Queue.
