### ISSUE TITLE
No module named 'Crypto'

### ISSUE THREAD

**Issue by NightFury135269** [anime-dl/anime-downloader#746]
**Describe the bug**

I just installed anime downloader on windows using choco but when i run dl command i get error No module named 'Crypto'
I think installing pycrypto might fix it but i read that it has some security issues and to use pycryptodome which is installed on my system but still getting the error

**To reproduce**

```
anime dl "Blue Lock"
```

<details>
<summary>LOG</summary>

```
 ~#@❯ anime --log-level DEBUG dl "Blue Lock"
2023-04-16 10:21:39 Night anime_downloader.util[7428] INFO anime-downloader 5.0.18
2023-04-16 10:21:39 Night anime_downloader.util[7428] DEBUG Platform: Windows-10-10.0.22621-SP0
2023-04-16 10:21:39 Night anime_downloader.util[7428] DEBUG Python 3.10.8
Traceback (most recent call last):
  File "C:\Users\kaust\AppData\Local\Programs\Python\Python310\Scripts\anime-script.py", line 33, in <module>
    sys.exit(load_entry_point('anime-downloader==5.0.18', 'console_scripts', 'anime')())
  File "C:\Users\kaust\AppData\Local\Programs\Python\Python310\lib\site-packages\anime_downloader\cli.py", line 81, in main
    cli()
  File "C:\Users\kaust\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\kaust\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\kaust\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\kaust\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\kaust\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\kaust\AppData\Roaming\Python\Python310\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\kaust\AppData\Local\Programs\Python\Python310\lib\site-packages\anime_downloader\commands\dl.py", line 118, in command
    anime_url, _ = util.search(anime_url, provider, choice)
  File "C:\Users\kaust\AppData\Local\Programs\Python\Python310\lib\site-packages\anime_downloader\util.py", line 94, in search
    cls = get_anime_class(provider)
  File "C:\Users\kaust\AppData\Local\Programs\Python\Python310\lib\site-packages\anime_downloader\sites\init.py", line 71, in get_anime_class
    module = import_module(
  File "C:\Users\kaust\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\kaust\AppData\Local\Programs\Python\Python310\lib\site-packages\anime_downloader\sites\twistmoe.py", line 1, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
```

**Comment by ArjixWasTaken** [comment]
![Screenshot_2023-04-16-13-57-00-420_com.github.android.jpg](https://user-images.githubusercontent.com/53124886/232302581-ba3952dc-6466-4c56-8810-405fce71ee0b.jpg)

**Comment by ArjixWasTaken** [comment]
Other than that, the default provider is twist.moe, which no longer exists and it required decryption.
